### ISSUE TITLE
Reconnection of BLE

### ISSUE THREAD

**Issue by Chuseuiti** [mjbrown/bgapi#16]
Lets imagine that Im connected to multiple BLE devices and I get disconnected from one of them. Is it possible to reconnected to a specific device without stopping all the connections to scan again? Is there a specific function for the reconnection?

**Comment by mjbrown** [comment]
Each connection is assigned a handle.  When you get the disconnect event it will provide you a handle so you know which one disconnected "ble_evt_connection_disconnected(self, connection, reason)"

You can save the advertisement/scan response you used to connect in the first place and re-use it.  Or, I believe you can scan again without disconnecting existing connections.  BlueGigaClient.connect assumes an advertisement/scan response for the target parameter.  It uses the address and address type for the ble_cmd_gap_connect_direct bgapi command.

**Comment by Chuseuiti** [comment]
Thanks, I have been able to scan while I was connected but I found it less effective compare when I scan without any device connected.

**Comment by Chuseuiti** [comment]
How could I
 get the actual device at the disconnection? because in the callback I get the connection but not the device that is related to that connection number

**Comment by mjbrown** [comment]
The BlueGigaClient.connect method returns a BLEConnection object.  That
object has the address of the connected device, as well as the BlueGiga
assigned connection handle.  Keep a dictionary or list of these objects,
and search through them to find the connection handle that disconnected.
You could even re-use that connection object as the target of the
BlueGigaClient.connect method and re-establish the connection.

After reconnecting, get rid of the old BLEConnection object since the new
connection may or may not have the previous connection handle.
